@startuml
!include ./nowl/nowl.iuml
class(c1, ns2:Plastic_Container)
class(c2, ns2:Shipment)
class(c3, ns2:Thermal_Forming_Operation)
class(c4, ns2:Plastic_Sheet)
class(c5, ns2:Sheet_Extrusion_Operation)
class(c6, ns2:Sheet_Extrusion_Machine)
class(c7, ns2:Sheet_Extrusion_Process)
class(c8, ns2:Thermal_Forming_Machine)
class(c9, ns2:Thermal_Forming_Process)
class(c10, ns2:Cooling_Process)
class(c11, ns2:CuttingTool)
class(c12, ns2:Trimming_Process)
class(c13, ns2:Die)
class(c14, ns2:Feeding_Process)
class(c15, ns2:Heating_Process)
class(c16, ns2:Mold)
class(c17, ns2:Melting_Process)
class(c18, ns2:plastic_Lid)
class(c19, ns2:Plastic_Lid)
class(c20, ns2:Rolling_Process)
individual(i1, ns1:Container_10x10x5)
individual(i2, ns1:S1)
individual(i3, ns1:TFOC1)
individual(i4, ns1:Container_10x16x4)
individual(i5, ns1:S2)
individual(i6, ns1:TFOC2)
individual(i7, ns1:PS1)
individual(i8, ns1:TFOL1)
individual(i9, ns1:TFOL2)
individual(i10, ns1:SEO1)
individual(i11, ns1:SEM1)
individual(i12, ns1:SEP1)
individual(i13, ns1:TFM1)
individual(i14, ns1:TFPC1)
individual(i15, ns1:TFPC2)
individual(i16, ns1:CPSE1)
individual(i17, ns1:CPTF1)
individual(i18, ns1:TFPL2)
individual(i19, ns1:CTC1)
individual(i20, ns1:TPC1)
individual(i21, ns1:CTC2)
individual(i22, ns1:TPC2)
individual(i23, ns1:CTL1)
individual(i24, ns1:TPL1)
individual(i25, ns1:CTL2)
individual(i26, ns1:TPL2)
individual(i27, ns1:D1)
individual(i28, ns1:FP1)
individual(i29, ns1:HP1)
individual(i30, ns1:MC1)
individual(i31, ns1:MC2)
individual(i32, ns1:ML1)
individual(i33, ns1:TFPL1)
individual(i34, ns1:ML2)
individual(i35, ns1:MP1)
individual(i36, ns1:PC1)
individual(i37, ns1:PC2)
individual(i38, ns1:PL1)
individual(i39, ns1:PL2)
individual(i40, ns1:Plastic_Lid_10x10x5)
individual(i41, ns1:Plastic_Lid_10x16x4)
individual(i42, ns1:RP1)
typeOf(i1, c1)
typeOf(i2, c2)
typeOf(i3, c3)
typeOf(i4, c1)
typeOf(i5, c2)
typeOf(i6, c3)
typeOf(i7, c4)
typeOf(i8, c3)
typeOf(i9, c3)
typeOf(i10, c5)
typeOf(i11, c6)
typeOf(i12, c7)
typeOf(i13, c8)
typeOf(i14, c9)
typeOf(i15, c9)
typeOf(i16, c10)
typeOf(i17, c10)
typeOf(i18, c9)
typeOf(i19, c11)
typeOf(i20, c12)
typeOf(i21, c11)
typeOf(i22, c12)
typeOf(i23, c11)
typeOf(i24, c12)
typeOf(i25, c11)
typeOf(i26, c12)
typeOf(i27, c13)
typeOf(i28, c14)
typeOf(i29, c15)
typeOf(i30, c16)
typeOf(i31, c16)
typeOf(i32, c16)
typeOf(i33, c9)
typeOf(i34, c16)
typeOf(i35, c17)
typeOf(i36, c1)
typeOf(i37, c1)
typeOf(i38, c18)
typeOf(i39, c18)
typeOf(i40, c19)
typeOf(i41, c19)
typeOf(i42, c20)
property(i1, ns2:is_output_of_at_some_time, i3)
property(i1, bfo:BFO_0000129, i2)
property(i3, bfo:BFO_0000132, i36)
property(i4, ns2:is_output_of_at_some_time, i6)
property(i4, bfo:BFO_0000129, i5)
property(i6, bfo:BFO_0000132, i37)
property(i7, ns2:is_output_of_at_some_time, i10)
property(i7, ns2:is_input_of_at_some_time, i3)
property(i7, ns2:is_input_of_at_some_time, i6)
property(i7, ns2:is_input_of_at_some_time, i8)
property(i7, ns2:is_input_of_at_some_time, i9)
property(i8, bfo:BFO_0000132, i38)
property(i9, bfo:BFO_0000132, i39)
property(i11, ns2:isResourceIn, i10)
property(i12, bfo:BFO_0000132, i10)
property(i13, ns2:isResourceIn, i3)
property(i13, ns2:isResourceIn, i6)
property(i13, ns2:isResourceIn, i8)
property(i13, ns2:isResourceIn, i9)
property(i14, bfo:BFO_0000132, i3)
property(i15, bfo:BFO_0000132, i6)
property(i16, bfo:BFO_0000132, i10)
property(i17, bfo:BFO_0000132, i3)
property(i17, bfo:BFO_0000132, i6)
property(i17, bfo:BFO_0000132, i8)
property(i17, bfo:BFO_0000132, i18)
property(i18, bfo:BFO_0000132, i9)
property(i19, bfo:BFO_0000056, i20)
property(i20, bfo:BFO_0000132, i3)
property(i21, bfo:BFO_0000056, i22)
property(i22, bfo:BFO_0000132, i6)
property(i23, bfo:BFO_0000056, i24)
property(i24, bfo:BFO_0000132, i8)
property(i25, bfo:BFO_0000056, i26)
property(i26, bfo:BFO_0000132, i9)
property(i27, bfo:BFO_0000056, i12)
property(i28, bfo:BFO_0000132, i3)
property(i28, bfo:BFO_0000132, i6)
property(i28, bfo:BFO_0000132, i8)
property(i28, bfo:BFO_0000132, i9)
property(i29, bfo:BFO_0000132, i3)
property(i29, bfo:BFO_0000132, i6)
property(i29, bfo:BFO_0000132, i8)
property(i29, bfo:BFO_0000132, i9)
property(i30, bfo:BFO_0000056, i14)
property(i31, bfo:BFO_0000056, i15)
property(i32, bfo:BFO_0000056, i33)
property(i33, bfo:BFO_0000132, i8)
property(i34, bfo:BFO_0000056, i18)
property(i35, bfo:BFO_0000132, i10)
property(i36, bfo:BFO_0000117, i10)
property(i36, bfo:BFO_0000117, i3)
property(i37, bfo:BFO_0000117, i10)
property(i37, bfo:BFO_0000117, i6)
property(i38, bfo:BFO_0000117, i10)
property(i38, bfo:BFO_0000117, i8)
property(i39, bfo:BFO_0000117, i10)
property(i39, bfo:BFO_0000117, i9)
property(i40, ns2:is_output_of_at_some_time, i8)
property(i40, bfo:BFO_0000129, i2)
property(i41, ns2:is_output_of_at_some_time, i9)
property(i41, bfo:BFO_0000129, i5)
property(i42, bfo:BFO_0000132, i10)
@enduml