PREFIX iof-av: <https://purl.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>


##
# banner Every class, object property and data property must have a definition in American English.


SELECT DISTINCT ?warning ?resource
WHERE
{
  ?resource rdf:type ?type.
  VALUES ?type {owl:Class owl:ObjectProperty owl:DatatypeProperty}
  FILTER NOT EXISTS {?resource iof-av:naturalLanguageDefinition ?definition. FILTER (langMatches(LANG(?label),"en-US"))}
  
  FILTER REGEX(STR(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
  
  BIND (CONCAT("PRODERROR: Resource ", STR(?resource), " does not have an iof:naturalLanguageDefinition in American English.") as ?warning)
}
