PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX cmns-av: <https://www.omg.org/spec/Commons/AnnotationVocabulary/>


##
# banner An ontology needs to have a label.


SELECT DISTINCT ?warning
WHERE 
{
  ?ont a owl:Ontology .
  FILTER NOT EXISTS {?ont owl:deprecated "true"^^xsd:boolean} .
  FILTER NOT EXISTS {?ont rdfs:label ?label.}

  FILTER regex(str(?ont), <HYGIENE_TESTS_FILTER_PARAMETER>)	

  BIND (CONCAT("WARNING:: Ontology ", STR(?ont), " does not have a label.") AS ?warning)
}
