PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>

PREFIX iof-av: <https://purl.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>

##
# banner Definitions must not start with articles.


SELECT DISTINCT (concat ("PRODERROR: definition ", str(?definition), " for ", STR(?resource) ," is ill-formed because it starts with an article.") AS ?warning)
WHERE
{
  ?resource rdf:type ?type.
  VALUES ?type {owl:Class owl:ObjectProperty owl:DatatypeProperty}

  ?resource iof-av:naturalLanguageDefinition ?definition. 
  FILTER (LANG(?label) = "en-US")
  FILTER (!STRSTARTS(?label, "a") || !STRSTARTS(?label, "an") || !STRSTARTS(?label, "the"))
  
	FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}

