PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>


##
# banner All labels for data properties should end with 'value' string.


SELECT DISTINCT (concat ("WARNING: Label ", str(?label), " for dataproperty ", STR(?resource) ," is ill-formed.") AS ?warning)
WHERE
{
  ?resource rdf:type owl:DatatypeProperty.
  ?resource rdfs:label ?label.
  FILTER (!STRENDS(?label, "value"))
  
	FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}

