PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


##
# Properties should not be punned.


SELECT DISTINCT (concat ("WARNING: Property ", str(?property), " is incorrectly punned.") AS ?warning) ?property
WHERE
{
    ?property rdf:type ?propertyType.
    FILTER (REGEX(STR(?propertyType), "ObjectProperty|AnnotationProperty|DatatypeProperty"))

    FILTER regex(str(?property), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
GROUP BY ?property
HAVING (COUNT(?propertyType) > 1)