all: MaintenanceDevRelationships.png MaintenanceDevRelationships-full.png MaintenanceDevRelationships-full-LTR.png MaintenanceDevRelationships-LTR.png 

%.png: ../plantuml/%.puml
	plantuml -o ../images $^
