@startuml
!include ./nowl/nowl.iuml
class(c1, ns2:MaterialArtifact)
class(c2, ns2:ProcessingStep)
class(c3, ns2:ManufacturingOperation)
class(c4, ns2:ProductionMachine)
class(c5, bfo:BFO_0000202)
class(c6, ns2:ValueExpression)
class(c7, ns2:TemporalDurationValueExpression)
individual(i1, ns1:ANC101)
individual(i2, ns1:ANC101_1_RECTANGULAR_POCKET_14_1)
individual(i3, ns1:ANC101_1_RECTANGULAR_POCKET_2_2)
individual(i4, ns1:ANC101_1_VMillMed)
individual(i5, ns1:VMillMed)
individual(i6, ns1:ANC101_1_RECTANGULAR_POCKET_14_1_TI)
individual(i7, ns1:ANC101_1_RECTANGULAR_POCKET_14_1_10)
individual(i8, ns1:ANC101_1_RECTANGULAR_POCKET_14_1_TDVI)
individual(i9, ns1:ANC101_1_RECTANGULAR_POCKET_2_2_20)
individual(i10, ns1:ANC101_1_RECTANGULAR_POCKET_2_2_TDVI)
individual(i11, ns1:ANC101_1_RECTANGULAR_POCKET_2_2_TI)
typeOf(i1, c1)
typeOf(i2, c2)
typeOf(i3, c2)
typeOf(i4, c3)
typeOf(i5, c4)
typeOf(i6, c5)
typeOf(i7, c6)
typeOf(i8, c7)
typeOf(i9, c6)
typeOf(i10, c7)
typeOf(i11, c5)
@enduml