application_config:
  display_license: false
  display_copyright: false
  license: 
    - 'http://purl.org/dc/terms/license'
  copyright:
    - 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/copyright'