PREFIX afn:   <http://jena.apache.org/ARQ/function#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>


#
# banner Every property (in a triple) should have its type explicitly declared.


SELECT DISTINCT ?warning
WHERE 
{
  ?subject ?property ?object.
  FILTER NOT EXISTS {?property rdf:type []}
  
  BIND (concat ("EDMC_WARN: Property ", STR(?property), " is used but has no type.") AS ?warning)

  FILTER regex(str(?property), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
