PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 


##
# banner IOF IRI should follow https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/4385505281/IRI+Structure+and+Format+2022-02


SELECT DISTINCT ?warning
WHERE
{
    ?ontology rdf:type owl:Ontology.

    FILTER (!regex(str(?ontology), 'https:\\/\\/[a-z\\/\\.]+\\/ontology\\/([a-z]+\\/)+([A-Z][a-z]+)+\\/'))

    FILTER regex(str(?ontology), <HYGIENE_TESTS_FILTER_PARAMETER>)

    BIND (CONCAT("EDMC_WARNING:: IRI for ontology ",STR(?ontology)," is ill-formed") as ?warning)
}