PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>

PREFIX iof-av: <https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>


##
# banner No definition may define more than one resource.


SELECT DISTINCT (concat ("PRODERROR: Definition <", str(?definition), "> defines multiple resources.") AS ?warning)
WHERE
{
  ?resource rdf:type ?type.
  VALUES ?type {owl:Class owl:ObjectProperty owl:DatatypeProperty}
  
  ?resource iof-av:naturalLanguageDefinition ?definition.
  
	FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
GROUP BY ?definition (LANG(?definition) as ?lang)
HAVING (COUNT(?resource) > 1)
