PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>

PREFIX iof-av: <https://purl.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>


##
# banner Every primitive class must have an FOL axiom.


SELECT DISTINCT ?warning ?resource
WHERE
{
  ?resource rdf:type owl:Class.
  ?resource iof-av:isPrimitive "true"^^xsd:boolean.
  
  FILTER NOT EXISTS 
  {
      ?resource iof-av:logicAxiom ?axioms.
      ?axioms iof-av:firstOrderLogicAxiom ?axiom.
  }

  FILTER REGEX(STR(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
  
  BIND (CONCAT("PRODERROR: A primitive class ", STR(?resource), " does not have an FOL axiom.") as ?warning)
}
