PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 


##
# banner IOF IRI should follow https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/4385505281/IRI+Structure+and+Format+2022-02


SELECT DISTINCT ?warning ?resource
WHERE
{
    ?resource ?property ?object.

    FILTER (!regex(str(?resource), '(spec|dev)\\.industrialontologies\\.org'))

    FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)

    BIND (CONCAT("WARN: IRI for resource ",STR(?resource)," has foreign authority prefix.") as ?warning)
}