PREFIX afn:   <http://jena.apache.org/ARQ/function#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>


#
# banner Every subject (in a triple) should have its type explicitly declared.


SELECT DISTINCT ?warning ?resource
WHERE 
{
  ?resource ?property ?object.
  FILTER NOT EXISTS {?resource rdf:type []}
  
  BIND (concat ("EDMC_WARN:", STR(?resource), " is referenced by ", afn:localname (?property), " but has no type.") AS ?warning)

  FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
}
