PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX iof-av: <https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>


##
# banner Every resource should have an example.


SELECT DISTINCT ?warning ?resource
WHERE
{
  ?resource rdf:type ?type.
  VALUES ?type {owl:Class owl:ObjectProperty owl:DatatypeProperty owl:AnnotationPropety}
  
  FILTER NOT EXISTS {?resource skos:example ?example.}
  
  FILTER REGEX(STR(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
  
  FILTER (!CONTAINS(STR(?resource),"https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/"))

  BIND (CONCAT("WARN: A resource ", STR(?resource), " does not have an example.") as ?warning)
}
