PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>

PREFIX iof-av: <https://purl.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>


##
# banner Every non-primitive class must have an FOL definition.


SELECT DISTINCT ?warning ?class
WHERE
{
  ?class rdf:type owl:Class.
  FILTER NOT EXISTS {?class iof-av:isPrimitive "true"^^xsd:boolean.}
  
  FILTER NOT EXISTS {?class iof-av:firstOrderLogicDefinition ?axiom.}
  
  FILTER REGEX(STR(?class), <HYGIENE_TESTS_FILTER_PARAMETER>)
  
  BIND (CONCAT("PRODERROR: A non-primitive class ", STR(?class), " does not have an FOL definition.") as ?warning)
}
