PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 


##
# banner An ontology must have a version IRI.


SELECT DISTINCT ?warning
WHERE 
{
  ?ont a owl:Ontology .
  FILTER NOT EXISTS {?ont owl:versionIRI ?versionIRI.}

  FILTER regex(str(?ont), <HYGIENE_TESTS_FILTER_PARAMETER>)	

  BIND (concat ("PRODERROR:: Ontology ", STR(?ont), " does not have a version IRI defined.") AS ?warning)
}
