PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dct: <http://purl.org/dc/terms/>

PREFIX iof-av: <https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/>

##
# banner An ontology must have a maturity level.


SELECT DISTINCT ?warning ?resource
WHERE 
{
  ?resource a owl:Ontology .
  FILTER NOT EXISTS {?resource iof-av:maturity ?maturityLevel.}

  FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)	

  BIND (concat ("PRODERROR: Ontology ", STR(?resource), " does not have a maturity level defined.") AS ?warning)
}
