@startuml
!include https://raw.githubusercontent.com/iofoundry/ontopuml/main/iof.iuml
class(c1, OperationSpecification)
class(c2, ProcessPlan)
class(c3, ProductionMachine)
class(c4, ProductionTool)
class(c5, SetupProcess)
class(c6, DrillingProcess)
class(c7, MillingProcess)
class(c8, InspectionProcess)
class(c9, MachineTransferProcess)
class(c10, ProcessingStep)
class(c11, ManufacturingOperation)
class(c12, PressingProcess)
individual(i1, ns1:operation1-spec)
individual(i2, ns1:operation2-spec)
individual(i3, ns1:operation3-spec)
individual(i4, ns1:process-plan1)
individual(i5, ns1:cnc-mill)
individual(i6, ns1:hydralic-press)
individual(i7, ns1:laser-marker)
individual(i8, ns1:twist-drill-bit)
individual(i9, ns1:carbide-end-mill)
individual(i10, ns1:setup1-on-machine1)
individual(i11, ns1:drilling)
individual(i12, ns1:setup2-on-machine1)
individual(i13, ns1:milling)
individual(i14, ns1:inspection1-after-cutting)
individual(i15, ns1:transfer1-to-press)
individual(i16, ns1:setup1-on-machine2)
individual(i17, ns1:step1-on-machine1)
individual(i18, ns1:step2-on-machine1)
individual(i19, ns1:operation1)
individual(i20, ns1:press-bending)
individual(i21, ns1:inspection1-afte-pressing)
individual(i22, ns1:transfer-to-marking)
individual(i23, ns1:laser-marking)
individual(i24, ns1:step1-on-machine2)
individual(i25, ns1:operation2)
individual(i26, ns1:final-inspection)
individual(i27, ns1:step1-on-machine3)
individual(i28, ns1:operation3)
typeOf(i1, c1)
typeOf(i2, c1)
typeOf(i3, c1)
typeOf(i4, c2)
typeOf(i5, c3)
typeOf(i6, c3)
typeOf(i7, c3)
typeOf(i8, c4)
typeOf(i9, c4)
typeOf(i10, c5)
typeOf(i11, c6)
typeOf(i12, c5)
typeOf(i13, c7)
typeOf(i14, c8)
typeOf(i15, c9)
typeOf(i16, c5)
typeOf(i17, c10)
typeOf(i18, c10)
typeOf(i19, c11)
typeOf(i20, c12)
typeOf(i21, c8)
typeOf(i22, c9)
typeOf(i23, c12)
typeOf(i24, c10)
typeOf(i25, c11)
typeOf(i26, c8)
typeOf(i27, c10)
typeOf(i28, c11)
property(i1, describes, i19)
property(i2, describes, i25)
property(i3, describes, i28)
property(i4, hasActionSpecificationAtAllTimes, i1)
property(i4, hasActionSpecificationAtAllTimes, i2)
property(i4, hasActionSpecificationAtAllTimes, i3)
property(i10, properOccurrentPartOf, i17)
property(i10, precedes, i11)
property(i11, properOccurrentPartOf, i17)
property(i11, precedes, i12)
property(i11, hasResource, i5)
property(i11, hasResource, i8)
property(i12, properOccurrentPartOf, i18)
property(i12, precedes, i13)
property(i13, properOccurrentPartOf, i18)
property(i13, precedes, i14)
property(i13, hasResource, i5)
property(i13, hasResource, i9)
property(i14, properOccurrentPartOf, i18)
property(i14, precedes, i15)
property(i15, precedes, i16)
property(i16, properOccurrentPartOf, i24)
property(i16, precedes, i20)
property(i17, properOccurrentPartOf, i19)
property(i18, properOccurrentPartOf, i19)
property(i20, properOccurrentPartOf, i24)
property(i20, precedes, i21)
property(i20, hasResource, i6)
property(i21, properOccurrentPartOf, i24)
property(i21, precedes, i22)
property(i22, precedes, i23)
property(i23, properOccurrentPartOf, i27)
property(i23, precedes, i26)
property(i23, hasResource, i7)
property(i24, properOccurrentPartOf, i25)
property(i27, properOccurrentPartOf, i28)
@enduml